// Lean compiler output
// Module: Lean.PrettyPrinter.Delaborator.DeclWithSig
// Imports: public import Lean.Parser.Types import Lean.Parser.Command
#include <lean/lean.h>
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wunused-label"
#elif defined(__GNUC__) && !defined(__CLANG__)
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#endif
#ifdef __cplusplus
extern "C" {
#endif
lean_object* l_Lean_Name_mkStr4(lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Parser_mkAntiquot_formatter___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Parser_Command_declSig_formatter___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
extern lean_object* l_Lean_Parser_maxPrec;
lean_object* l_Lean_Parser_termParser_formatter___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_PrettyPrinter_Formatter_andthen_formatter___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Parser_leadingNode_formatter___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_PrettyPrinter_Formatter_orelse_formatter(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Name_mkStr5(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Parser_Command_declSig_parenthesizer___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Parser_termParser_parenthesizer___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_PrettyPrinter_Parenthesizer_andthen_parenthesizer___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_PrettyPrinter_Parenthesizer_leadingNode_parenthesizer___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Parser_mkAntiquot_parenthesizer___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_PrettyPrinter_Parenthesizer_withAntiquot_parenthesizer(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
extern lean_object* l_Lean_PrettyPrinter_parenthesizerAttribute;
lean_object* l_Lean_KeyedDeclsAttribute_addBuiltin___redArg(lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Parser_mkAntiquot(lean_object*, lean_object*, uint8_t, uint8_t);
lean_object* l_Lean_Parser_termParser(lean_object*);
extern lean_object* l_Lean_Parser_Command_declSig;
lean_object* l_Lean_Parser_andthen(lean_object*, lean_object*);
lean_object* l_Lean_Parser_leadingNode(lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Parser_withAntiquot(lean_object*, lean_object*);
extern lean_object* l_Lean_PrettyPrinter_formatterAttribute;
lean_object* l_Lean_Parser_withCache(lean_object*, lean_object*);
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__0_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__0;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__1_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__1;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__2_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__2;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__5_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__5;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__6_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__6;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__7_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__7;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__8_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__8;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__9_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__9;
LEAN_EXPORT lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter(lean_object*, lean_object*, lean_object*, lean_object*);
LEAN_EXPORT lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
static lean_once_cell_t l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___closed__0_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___closed__0;
static lean_once_cell_t l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___closed__1_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___closed__1;
LEAN_EXPORT lean_object* l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3();
LEAN_EXPORT lean_object* l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___boxed(lean_object*);
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__0_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__0;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__1_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__1;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__2_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__2;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__3_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__3;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__4_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__4;
LEAN_EXPORT lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer(lean_object*, lean_object*, lean_object*, lean_object*);
LEAN_EXPORT lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
static lean_once_cell_t l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___closed__0_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___closed__0;
static lean_once_cell_t l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___closed__1_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___closed__1;
LEAN_EXPORT lean_object* l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7();
LEAN_EXPORT lean_object* l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___boxed(lean_object*);
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__0_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__0;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__1_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__1;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__2_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__2;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__3_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__3;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__4_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__4;
static lean_once_cell_t l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__5_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__5;
LEAN_EXPORT lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId;
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__0(void){
_start:
{
lean_object* v___x_1_; 
v___x_1_ = lean_mk_string_unchecked("Lean", 4, 4);
return v___x_1_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__1(void){
_start:
{
lean_object* v___x_2_; 
v___x_2_ = lean_mk_string_unchecked("PrettyPrinter", 13, 13);
return v___x_2_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__2(void){
_start:
{
lean_object* v___x_3_; 
v___x_3_ = lean_mk_string_unchecked("Delaborator", 11, 11);
return v___x_3_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3(void){
_start:
{
lean_object* v___x_4_; 
v___x_4_ = lean_mk_string_unchecked("declSigWithId", 13, 13);
return v___x_4_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4(void){
_start:
{
lean_object* v___x_5_; lean_object* v___x_6_; lean_object* v___x_7_; lean_object* v___x_8_; lean_object* v___x_9_; 
v___x_5_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3);
v___x_6_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__2, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__2_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__2);
v___x_7_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__1, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__1_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__1);
v___x_8_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__0, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__0_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__0);
v___x_9_ = l_Lean_Name_mkStr4(v___x_8_, v___x_7_, v___x_6_, v___x_5_);
return v___x_9_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__5(void){
_start:
{
uint8_t v___x_10_; uint8_t v___x_11_; lean_object* v___x_12_; lean_object* v___x_13_; lean_object* v___x_14_; lean_object* v___x_15_; lean_object* v___x_16_; 
v___x_10_ = 0;
v___x_11_ = 1;
v___x_12_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4);
v___x_13_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3);
v___x_14_ = lean_box(v___x_11_);
v___x_15_ = lean_box(v___x_10_);
v___x_16_ = lean_alloc_closure((void*)(l_Lean_Parser_mkAntiquot_formatter___boxed), 9, 4);
lean_closure_set(v___x_16_, 0, v___x_13_);
lean_closure_set(v___x_16_, 1, v___x_12_);
lean_closure_set(v___x_16_, 2, v___x_14_);
lean_closure_set(v___x_16_, 3, v___x_15_);
return v___x_16_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__6(void){
_start:
{
lean_object* v___x_17_; lean_object* v___x_18_; 
v___x_17_ = l_Lean_Parser_maxPrec;
v___x_18_ = lean_alloc_closure((void*)(l_Lean_Parser_termParser_formatter___boxed), 6, 1);
lean_closure_set(v___x_18_, 0, v___x_17_);
return v___x_18_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__7(void){
_start:
{
lean_object* v___x_19_; 
v___x_19_ = lean_alloc_closure((void*)(l_Lean_Parser_Command_declSig_formatter___boxed), 5, 0);
return v___x_19_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__8(void){
_start:
{
lean_object* v___x_20_; lean_object* v___x_21_; lean_object* v___x_22_; 
v___x_20_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__7, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__7_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__7);
v___x_21_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__6, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__6_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__6);
v___x_22_ = lean_alloc_closure((void*)(l_Lean_PrettyPrinter_Formatter_andthen_formatter___boxed), 7, 2);
lean_closure_set(v___x_22_, 0, v___x_21_);
lean_closure_set(v___x_22_, 1, v___x_20_);
return v___x_22_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__9(void){
_start:
{
lean_object* v___x_23_; lean_object* v___x_24_; lean_object* v___x_25_; lean_object* v___x_26_; 
v___x_23_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__8, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__8_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__8);
v___x_24_ = lean_unsigned_to_nat(1024u);
v___x_25_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4);
v___x_26_ = lean_alloc_closure((void*)(l_Lean_Parser_leadingNode_formatter___boxed), 8, 3);
lean_closure_set(v___x_26_, 0, v___x_25_);
lean_closure_set(v___x_26_, 1, v___x_24_);
lean_closure_set(v___x_26_, 2, v___x_23_);
return v___x_26_;
}
}
LEAN_EXPORT lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter(lean_object* v_a_27_, lean_object* v_a_28_, lean_object* v_a_29_, lean_object* v_a_30_){
_start:
{
lean_object* v___x_32_; lean_object* v___x_33_; lean_object* v___x_34_; 
v___x_32_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__5, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__5_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__5);
v___x_33_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__9, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__9_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__9);
v___x_34_ = l_Lean_PrettyPrinter_Formatter_orelse_formatter(v___x_32_, v___x_33_, v_a_27_, v_a_28_, v_a_29_, v_a_30_);
return v___x_34_;
}
}
LEAN_EXPORT lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___boxed(lean_object* v_a_35_, lean_object* v_a_36_, lean_object* v_a_37_, lean_object* v_a_38_, lean_object* v_a_39_){
_start:
{
lean_object* v_res_40_; 
v_res_40_ = l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter(v_a_35_, v_a_36_, v_a_37_, v_a_38_);
lean_dec(v_a_38_);
lean_dec_ref(v_a_37_);
lean_dec(v_a_36_);
lean_dec_ref(v_a_35_);
return v_res_40_;
}
}
static lean_object* _init_l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___closed__0(void){
_start:
{
lean_object* v___x_41_; 
v___x_41_ = lean_mk_string_unchecked("formatter", 9, 9);
return v___x_41_;
}
}
static lean_object* _init_l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___closed__1(void){
_start:
{
lean_object* v___x_42_; lean_object* v___x_43_; lean_object* v___x_44_; lean_object* v___x_45_; lean_object* v___x_46_; lean_object* v___x_47_; 
v___x_42_ = lean_obj_once(&l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___closed__0, &l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___closed__0_once, _init_l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___closed__0);
v___x_43_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3);
v___x_44_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__2, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__2_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__2);
v___x_45_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__1, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__1_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__1);
v___x_46_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__0, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__0_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__0);
v___x_47_ = l_Lean_Name_mkStr5(v___x_46_, v___x_45_, v___x_44_, v___x_43_, v___x_42_);
return v___x_47_;
}
}
LEAN_EXPORT lean_object* l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3(){
_start:
{
lean_object* v___x_49_; lean_object* v___x_50_; lean_object* v___x_51_; lean_object* v___x_52_; lean_object* v___x_53_; 
v___x_49_ = l_Lean_PrettyPrinter_formatterAttribute;
v___x_50_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4);
v___x_51_ = lean_obj_once(&l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___closed__1, &l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___closed__1_once, _init_l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___closed__1);
v___x_52_ = lean_alloc_closure((void*)(l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___boxed), 5, 0);
v___x_53_ = l_Lean_KeyedDeclsAttribute_addBuiltin___redArg(v___x_49_, v___x_50_, v___x_51_, v___x_52_);
return v___x_53_;
}
}
LEAN_EXPORT lean_object* l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3___boxed(lean_object* v_a_54_){
_start:
{
lean_object* v_res_55_; 
v_res_55_ = l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3();
return v_res_55_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__0(void){
_start:
{
uint8_t v___x_56_; uint8_t v___x_57_; lean_object* v___x_58_; lean_object* v___x_59_; lean_object* v___x_60_; lean_object* v___x_61_; lean_object* v___x_62_; 
v___x_56_ = 0;
v___x_57_ = 1;
v___x_58_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4);
v___x_59_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3);
v___x_60_ = lean_box(v___x_57_);
v___x_61_ = lean_box(v___x_56_);
v___x_62_ = lean_alloc_closure((void*)(l_Lean_Parser_mkAntiquot_parenthesizer___boxed), 9, 4);
lean_closure_set(v___x_62_, 0, v___x_59_);
lean_closure_set(v___x_62_, 1, v___x_58_);
lean_closure_set(v___x_62_, 2, v___x_60_);
lean_closure_set(v___x_62_, 3, v___x_61_);
return v___x_62_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__1(void){
_start:
{
lean_object* v___x_63_; lean_object* v___x_64_; 
v___x_63_ = l_Lean_Parser_maxPrec;
v___x_64_ = lean_alloc_closure((void*)(l_Lean_Parser_termParser_parenthesizer___boxed), 6, 1);
lean_closure_set(v___x_64_, 0, v___x_63_);
return v___x_64_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__2(void){
_start:
{
lean_object* v___x_65_; 
v___x_65_ = lean_alloc_closure((void*)(l_Lean_Parser_Command_declSig_parenthesizer___boxed), 5, 0);
return v___x_65_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__3(void){
_start:
{
lean_object* v___x_66_; lean_object* v___x_67_; lean_object* v___x_68_; 
v___x_66_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__2, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__2_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__2);
v___x_67_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__1, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__1_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__1);
v___x_68_ = lean_alloc_closure((void*)(l_Lean_PrettyPrinter_Parenthesizer_andthen_parenthesizer___boxed), 7, 2);
lean_closure_set(v___x_68_, 0, v___x_67_);
lean_closure_set(v___x_68_, 1, v___x_66_);
return v___x_68_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__4(void){
_start:
{
lean_object* v___x_69_; lean_object* v___x_70_; lean_object* v___x_71_; lean_object* v___x_72_; 
v___x_69_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__3, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__3_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__3);
v___x_70_ = lean_unsigned_to_nat(1024u);
v___x_71_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4);
v___x_72_ = lean_alloc_closure((void*)(l_Lean_PrettyPrinter_Parenthesizer_leadingNode_parenthesizer___boxed), 8, 3);
lean_closure_set(v___x_72_, 0, v___x_71_);
lean_closure_set(v___x_72_, 1, v___x_70_);
lean_closure_set(v___x_72_, 2, v___x_69_);
return v___x_72_;
}
}
LEAN_EXPORT lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer(lean_object* v_a_73_, lean_object* v_a_74_, lean_object* v_a_75_, lean_object* v_a_76_){
_start:
{
lean_object* v___x_78_; lean_object* v___x_79_; lean_object* v___x_80_; 
v___x_78_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__0, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__0_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__0);
v___x_79_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__4, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__4_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___closed__4);
v___x_80_ = l_Lean_PrettyPrinter_Parenthesizer_withAntiquot_parenthesizer(v___x_78_, v___x_79_, v_a_73_, v_a_74_, v_a_75_, v_a_76_);
return v___x_80_;
}
}
LEAN_EXPORT lean_object* l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___boxed(lean_object* v_a_81_, lean_object* v_a_82_, lean_object* v_a_83_, lean_object* v_a_84_, lean_object* v_a_85_){
_start:
{
lean_object* v_res_86_; 
v_res_86_ = l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer(v_a_81_, v_a_82_, v_a_83_, v_a_84_);
lean_dec(v_a_84_);
lean_dec_ref(v_a_83_);
lean_dec(v_a_82_);
lean_dec_ref(v_a_81_);
return v_res_86_;
}
}
static lean_object* _init_l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___closed__0(void){
_start:
{
lean_object* v___x_87_; 
v___x_87_ = lean_mk_string_unchecked("parenthesizer", 13, 13);
return v___x_87_;
}
}
static lean_object* _init_l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___closed__1(void){
_start:
{
lean_object* v___x_88_; lean_object* v___x_89_; lean_object* v___x_90_; lean_object* v___x_91_; lean_object* v___x_92_; lean_object* v___x_93_; 
v___x_88_ = lean_obj_once(&l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___closed__0, &l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___closed__0_once, _init_l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___closed__0);
v___x_89_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3);
v___x_90_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__2, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__2_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__2);
v___x_91_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__1, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__1_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__1);
v___x_92_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__0, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__0_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__0);
v___x_93_ = l_Lean_Name_mkStr5(v___x_92_, v___x_91_, v___x_90_, v___x_89_, v___x_88_);
return v___x_93_;
}
}
LEAN_EXPORT lean_object* l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7(){
_start:
{
lean_object* v___x_95_; lean_object* v___x_96_; lean_object* v___x_97_; lean_object* v___x_98_; lean_object* v___x_99_; 
v___x_95_ = l_Lean_PrettyPrinter_parenthesizerAttribute;
v___x_96_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4);
v___x_97_ = lean_obj_once(&l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___closed__1, &l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___closed__1_once, _init_l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___closed__1);
v___x_98_ = lean_alloc_closure((void*)(l_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer___boxed), 5, 0);
v___x_99_ = l_Lean_KeyedDeclsAttribute_addBuiltin___redArg(v___x_95_, v___x_96_, v___x_97_, v___x_98_);
return v___x_99_;
}
}
LEAN_EXPORT lean_object* l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7___boxed(lean_object* v_a_100_){
_start:
{
lean_object* v_res_101_; 
v_res_101_ = l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7();
return v_res_101_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__0(void){
_start:
{
uint8_t v___x_102_; uint8_t v___x_103_; lean_object* v___x_104_; lean_object* v___x_105_; lean_object* v___x_106_; 
v___x_102_ = 0;
v___x_103_ = 1;
v___x_104_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4);
v___x_105_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__3);
v___x_106_ = l_Lean_Parser_mkAntiquot(v___x_105_, v___x_104_, v___x_103_, v___x_102_);
return v___x_106_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__1(void){
_start:
{
lean_object* v___x_107_; lean_object* v___x_108_; 
v___x_107_ = l_Lean_Parser_maxPrec;
v___x_108_ = l_Lean_Parser_termParser(v___x_107_);
return v___x_108_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__2(void){
_start:
{
lean_object* v___x_109_; lean_object* v___x_110_; lean_object* v___x_111_; 
v___x_109_ = l_Lean_Parser_Command_declSig;
v___x_110_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__1, &l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__1_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__1);
v___x_111_ = l_Lean_Parser_andthen(v___x_110_, v___x_109_);
return v___x_111_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__3(void){
_start:
{
lean_object* v___x_112_; lean_object* v___x_113_; lean_object* v___x_114_; lean_object* v___x_115_; 
v___x_112_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__2, &l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__2_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__2);
v___x_113_ = lean_unsigned_to_nat(1024u);
v___x_114_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4);
v___x_115_ = l_Lean_Parser_leadingNode(v___x_114_, v___x_113_, v___x_112_);
return v___x_115_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__4(void){
_start:
{
lean_object* v___x_116_; lean_object* v___x_117_; lean_object* v___x_118_; 
v___x_116_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__3, &l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__3_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__3);
v___x_117_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__0, &l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__0_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__0);
v___x_118_ = l_Lean_Parser_withAntiquot(v___x_117_, v___x_116_);
return v___x_118_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__5(void){
_start:
{
lean_object* v___x_119_; lean_object* v___x_120_; lean_object* v___x_121_; 
v___x_119_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__4, &l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__4_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__4);
v___x_120_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4, &l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter___closed__4);
v___x_121_ = l_Lean_Parser_withCache(v___x_120_, v___x_119_);
return v___x_121_;
}
}
static lean_object* _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId(void){
_start:
{
lean_object* v___x_122_; 
v___x_122_ = lean_obj_once(&l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__5, &l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__5_once, _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId___closed__5);
return v___x_122_;
}
}
lean_object* runtime_initialize_Lean_Parser_Types(uint8_t builtin);
lean_object* runtime_initialize_Lean_Parser_Command(uint8_t builtin);
static bool _G_runtime_initialized = false;
LEAN_EXPORT lean_object* runtime_initialize_Lean_PrettyPrinter_Delaborator_DeclWithSig(uint8_t builtin) {
lean_object * res;
if (_G_runtime_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_runtime_initialized = true;
res = runtime_initialize_Lean_Parser_Types(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_Lean_Parser_Command(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_formatter__3();
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = l___private_Lean_PrettyPrinter_Delaborator_DeclWithSig_0__Lean_PrettyPrinter_Delaborator_declSigWithId___regBuiltin_Lean_PrettyPrinter_Delaborator_declSigWithId_parenthesizer__7();
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
l_Lean_PrettyPrinter_Delaborator_declSigWithId = _init_l_Lean_PrettyPrinter_Delaborator_declSigWithId();
lean_mark_persistent(l_Lean_PrettyPrinter_Delaborator_declSigWithId);
return lean_io_result_mk_ok(lean_box(0));
}
static bool _G_meta_initialized = false;
LEAN_EXPORT lean_object* meta_initialize_Lean_PrettyPrinter_Delaborator_DeclWithSig(uint8_t builtin) {
lean_object * res;
if (_G_meta_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_meta_initialized = true;
return lean_io_result_mk_ok(lean_box(0));
}
lean_object* initialize_Lean_Parser_Types(uint8_t builtin);
lean_object* initialize_Lean_Parser_Command(uint8_t builtin);
static bool _G_initialized = false;
LEAN_EXPORT lean_object* initialize_Lean_PrettyPrinter_Delaborator_DeclWithSig(uint8_t builtin) {
lean_object * res;
if (_G_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_initialized = true;
res = initialize_Lean_Parser_Types(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Lean_Parser_Command(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_Lean_PrettyPrinter_Delaborator_DeclWithSig(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = meta_initialize_Lean_PrettyPrinter_Delaborator_DeclWithSig(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
return initialize_Lean_PrettyPrinter_Delaborator_DeclWithSig(builtin);
}
#ifdef __cplusplus
}
#endif
