/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Graf, Robin Arnez
-/
module

prelude
public import Init.Internal.Order.Basic
public import Init.Internal.Order.MonadTail
import Init.Classical

set_option linter.missingDocs true

/-!
This module provides a fixpoint combinator that combines advantages of `partial` and
`partial_fixpoint` recursion.

The combinator is similar to {lean}`CCPO.fix`, but does not require a CCPO instance or
monotonicity proof at the definition site. Therefore, it can be used in situations in which
these constraints are unavailable (e.g., when the monad does not have a `MonadTail` instance).
Given a CCPO and monotonicity proof, there are theorems guaranteeing that it equals
{lean}`CCPO.fix` and satisfies fixpoint induction.
-/

public section

namespace Lean.Order

/--
The function implemented as the loop {lean}`opaqueFix f = f (opaqueFix f)`.
{lean}`opaqueFix f` is the fixpoint of {name}`f`, as long as `f` is monotone with respect to
some CCPO on `α`.

The loop might run forever depending on {name}`f`. It is opaque, i.e., it is impossible to prove
nontrivial properties about it.
-/
@[specialize]
partial def opaqueFix {α : Sort u} [Nonempty α] (f : α → α) : α :=
  f (opaqueFix f)

/-
SAFE assuming that the code generated by iteration over `f` is equivalent to the CCPO
fixpoint of `f` if there exists a CCPO making `f` monotone.
-/
open _root_.Classical in
/--
A fixpoint combinator that can be used to construct recursive definitions with an *extrinsic*
proof of monotonicity.

Given a fixpoint functional {name}`f`, {lean}`extrinsicFix f` is the recursive function obtained
by having {name}`f` call itself recursively.

If there is no CCPO on `α` making {name}`f` monotone, {lean}`extrinsicFix f` might run forever.
In this case, nothing interesting can be proved about the result; it is opaque.

If there _is_ a CCPO on `α` making {name}`f` monotone, {lean}`extrinsicFix f` is equivalent to
{lean}`CCPO.fix f`, logically and regarding its termination behavior.
-/
@[cbv_opaque, implemented_by opaqueFix]
def extrinsicFix {α : Sort u} [Nonempty α] (f : α → α) : α :=
  if h : ∃ x, x = f x then
    h.choose
  else
    -- Return `opaqueFix f` so that `implemented_by opaqueFix` is sound.
    -- In effect, `extrinsicFix` is opaque if no fixpoint exists.
    opaqueFix f

/--
A fixpoint combinator that allows for deferred proofs of monotonicity.

{lean}`extrinsicFix f` is a function implemented as the loop
{lean}`extrinsicFix f = f (extrinsicFix f)`.

If there is a CCPO making `f` monotone, {name}`extrinsicFix_eq` proves that it satisfies the
fixpoint equation, and {name}`extrinsicFix_induct` enables fixpoint induction.
Otherwise, {lean}`extrinsicFix f` is opaque, i.e., it is impossible to prove nontrivial
properties about it.
-/
add_decl_doc extrinsicFix

/-- Every CCPO has at least one element (the bottom element). -/
noncomputable local instance CCPO.instNonempty [CCPO α] : Nonempty α := ⟨bot⟩

/--
The fixpoint equation for `extrinsicFix`: given a proof that the fixpoint exists, unfold
`extrinsicFix`.
-/
theorem extrinsicFix_eq {f : α → α}
    (x : α) (h : x = f x) :
    letI : Nonempty α := ⟨x⟩; extrinsicFix f = f (extrinsicFix f) := by
  letI : Nonempty α := ⟨x⟩
  have h : ∃ x, x = f x := ⟨x, h⟩
  simp only [extrinsicFix, dif_pos h]
  exact h.choose_spec

/--
The fixpoint equation for `extrinsicFix`: given a CCPO instance and monotonicity of `f`,
{lean}`extrinsicFix f = f (extrinsicFix f)`.
-/
theorem extrinsicFix_eq_mono [inst : CCPO α] {f : α → α}
    (hf : monotone f) :
    extrinsicFix f = f (extrinsicFix f) :=
  extrinsicFix_eq (fix f hf) (fix_eq hf)

abbrev discardR {C : α → Sort _} {R : α → α → Prop}
    (f : ∀ a, (∀ a', R a' a → C a') → C a) : ((∀ a, C a) → (∀ a, C a)) :=
  fun rec a => f a (fun a _ => rec a)

theorem extrinsicFix_eq_wf {C : α → Sort _} [∀ a, Nonempty (C a)] {R : α → α → Prop}
    {f : ∀ a, (∀ a', R a' a → C a') → C a} (h : WellFounded R) {a : α} :
    extrinsicFix (discardR f) a = f a (fun a _ => extrinsicFix (discardR f) a) := by
  suffices extrinsicFix (discardR f) = fun a => f a (fun a _ => extrinsicFix (discardR f) a) by
    conv => lhs; rw [this]
  apply extrinsicFix_eq (fun a => WellFounded.fix h f a) (funext fun a => (WellFounded.fix_eq h f a))

end Lean.Order
