// Lean compiler output
// Module: Init.MacroTrace
// Imports: public meta import Init.Meta public import Init.Notation import Init.Data.ToString.Macro
#include <lean/lean.h>
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wunused-label"
#elif defined(__GNUC__) && !defined(__CLANG__)
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#endif
#ifdef __cplusplus
extern "C" {
#endif
lean_object* l_Lean_Name_mkStr4(lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Name_mkStr2(lean_object*, lean_object*);
uint8_t l_Lean_Syntax_isOfKind(lean_object*, lean_object*);
lean_object* l_Lean_Syntax_getArg(lean_object*, lean_object*);
lean_object* l_Lean_SourceInfo_fromRef(lean_object*, uint8_t);
lean_object* l_String_toRawSubstring_x27(lean_object*);
lean_object* l_Lean_addMacroScope(lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Name_mkStr3(lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Name_mkStr1(lean_object*);
lean_object* l_Lean_Syntax_node1(lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Syntax_node2(lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Syntax_node3(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_TSyntax_getId(lean_object*);
lean_object* lean_erase_macro_scopes(lean_object*);
lean_object* l___private_Init_Meta_Defs_0__Lean_getEscapedNameParts_x3f(lean_object*, lean_object*);
lean_object* l_Lean_quoteNameMk(lean_object*);
lean_object* lean_string_intercalate(lean_object*, lean_object*);
lean_object* lean_string_append(lean_object*, lean_object*);
lean_object* l_Lean_Syntax_mkNameLit(lean_object*, lean_object*);
lean_object* lean_mk_empty_array_with_capacity(lean_object*);
lean_object* lean_array_push(lean_object*, lean_object*);
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__1_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__1;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__2_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__2;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__3_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__3;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__4_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__4;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__5_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__5;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__6_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__6;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__7_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__7;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__8_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__8;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__9_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__9;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__10_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__10;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__11_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__11;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__12_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__12;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__13_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__13;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__14_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__14;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__15_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__15;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__16_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__16;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__17_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__17;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__18_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__18;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__19_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__19;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__20_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__20;
static lean_once_cell_t l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__21_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__21;
LEAN_EXPORT lean_object* l_Lean_termMacro_x2etrace_x5b___x5d__;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__2_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__2;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__3_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__3;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__4_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__4;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__5_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__5;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__6_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__6;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__7_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__7;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__8_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__8;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__9_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__9;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__10_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__10;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__11_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__11;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__12_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__12;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__13_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__13;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__14_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__14;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__15_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__15;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__16_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__16;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__17_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__17;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__18_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__18;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__19_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__19;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__20_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__20;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__21_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__21;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__22_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__22;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__23_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__23;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__24_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__24;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__25_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__25;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__26_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__26;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__27_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__27;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__28_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__28;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__29_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__29;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__30_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__30;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__31_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__31;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__32_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__32;
static lean_once_cell_t l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__33_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__33;
LEAN_EXPORT lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1(lean_object*, lean_object*, lean_object*);
LEAN_EXPORT lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___boxed(lean_object*, lean_object*, lean_object*);
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0(void){
_start:
{
lean_object* v___x_1_; 
v___x_1_ = lean_mk_string_unchecked("Lean", 4, 4);
return v___x_1_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__1(void){
_start:
{
lean_object* v___x_2_; 
v___x_2_ = lean_mk_string_unchecked("termMacro.trace[_]_", 19, 19);
return v___x_2_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__2(void){
_start:
{
lean_object* v___x_3_; lean_object* v___x_4_; lean_object* v___x_5_; 
v___x_3_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__1, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__1_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__1);
v___x_4_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0);
v___x_5_ = l_Lean_Name_mkStr2(v___x_4_, v___x_3_);
return v___x_5_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__3(void){
_start:
{
lean_object* v___x_6_; 
v___x_6_ = lean_mk_string_unchecked("andthen", 7, 7);
return v___x_6_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__4(void){
_start:
{
lean_object* v___x_7_; lean_object* v___x_8_; 
v___x_7_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__3, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__3_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__3);
v___x_8_ = l_Lean_Name_mkStr1(v___x_7_);
return v___x_8_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__5(void){
_start:
{
lean_object* v___x_9_; 
v___x_9_ = lean_mk_string_unchecked("Macro.trace[", 12, 12);
return v___x_9_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__6(void){
_start:
{
lean_object* v___x_10_; lean_object* v___x_11_; 
v___x_10_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__5, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__5_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__5);
v___x_11_ = lean_alloc_ctor(5, 1, 0);
lean_ctor_set(v___x_11_, 0, v___x_10_);
return v___x_11_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__7(void){
_start:
{
lean_object* v___x_12_; 
v___x_12_ = lean_mk_string_unchecked("ident", 5, 5);
return v___x_12_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__8(void){
_start:
{
lean_object* v___x_13_; lean_object* v___x_14_; 
v___x_13_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__7, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__7_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__7);
v___x_14_ = l_Lean_Name_mkStr1(v___x_13_);
return v___x_14_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__9(void){
_start:
{
lean_object* v___x_15_; lean_object* v___x_16_; 
v___x_15_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__8, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__8_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__8);
v___x_16_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v___x_16_, 0, v___x_15_);
return v___x_16_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__10(void){
_start:
{
lean_object* v___x_17_; lean_object* v___x_18_; lean_object* v___x_19_; lean_object* v___x_20_; 
v___x_17_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__9, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__9_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__9);
v___x_18_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__6, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__6_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__6);
v___x_19_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__4, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__4_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__4);
v___x_20_ = lean_alloc_ctor(2, 3, 0);
lean_ctor_set(v___x_20_, 0, v___x_19_);
lean_ctor_set(v___x_20_, 1, v___x_18_);
lean_ctor_set(v___x_20_, 2, v___x_17_);
return v___x_20_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__11(void){
_start:
{
lean_object* v___x_21_; 
v___x_21_ = lean_mk_string_unchecked("]", 1, 1);
return v___x_21_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__12(void){
_start:
{
lean_object* v___x_22_; lean_object* v___x_23_; 
v___x_22_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__11, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__11_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__11);
v___x_23_ = lean_alloc_ctor(5, 1, 0);
lean_ctor_set(v___x_23_, 0, v___x_22_);
return v___x_23_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__13(void){
_start:
{
lean_object* v___x_24_; lean_object* v___x_25_; lean_object* v___x_26_; lean_object* v___x_27_; 
v___x_24_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__12, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__12_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__12);
v___x_25_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__10, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__10_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__10);
v___x_26_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__4, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__4_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__4);
v___x_27_ = lean_alloc_ctor(2, 3, 0);
lean_ctor_set(v___x_27_, 0, v___x_26_);
lean_ctor_set(v___x_27_, 1, v___x_25_);
lean_ctor_set(v___x_27_, 2, v___x_24_);
return v___x_27_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__14(void){
_start:
{
lean_object* v___x_28_; 
v___x_28_ = lean_mk_string_unchecked("interpolatedStr", 15, 15);
return v___x_28_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__15(void){
_start:
{
lean_object* v___x_29_; lean_object* v___x_30_; 
v___x_29_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__14, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__14_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__14);
v___x_30_ = l_Lean_Name_mkStr1(v___x_29_);
return v___x_30_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__16(void){
_start:
{
lean_object* v___x_31_; 
v___x_31_ = lean_mk_string_unchecked("term", 4, 4);
return v___x_31_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__17(void){
_start:
{
lean_object* v___x_32_; lean_object* v___x_33_; 
v___x_32_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__16, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__16_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__16);
v___x_33_ = l_Lean_Name_mkStr1(v___x_32_);
return v___x_33_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__18(void){
_start:
{
lean_object* v___x_34_; lean_object* v___x_35_; lean_object* v___x_36_; 
v___x_34_ = lean_unsigned_to_nat(0u);
v___x_35_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__17, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__17_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__17);
v___x_36_ = lean_alloc_ctor(7, 2, 0);
lean_ctor_set(v___x_36_, 0, v___x_35_);
lean_ctor_set(v___x_36_, 1, v___x_34_);
return v___x_36_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__19(void){
_start:
{
lean_object* v___x_37_; lean_object* v___x_38_; lean_object* v___x_39_; 
v___x_37_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__18, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__18_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__18);
v___x_38_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__15, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__15_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__15);
v___x_39_ = lean_alloc_ctor(1, 2, 0);
lean_ctor_set(v___x_39_, 0, v___x_38_);
lean_ctor_set(v___x_39_, 1, v___x_37_);
return v___x_39_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__20(void){
_start:
{
lean_object* v___x_40_; lean_object* v___x_41_; lean_object* v___x_42_; lean_object* v___x_43_; 
v___x_40_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__19, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__19_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__19);
v___x_41_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__13, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__13_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__13);
v___x_42_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__4, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__4_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__4);
v___x_43_ = lean_alloc_ctor(2, 3, 0);
lean_ctor_set(v___x_43_, 0, v___x_42_);
lean_ctor_set(v___x_43_, 1, v___x_41_);
lean_ctor_set(v___x_43_, 2, v___x_40_);
return v___x_43_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__21(void){
_start:
{
lean_object* v___x_44_; lean_object* v___x_45_; lean_object* v___x_46_; lean_object* v___x_47_; 
v___x_44_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__20, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__20_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__20);
v___x_45_ = lean_unsigned_to_nat(1022u);
v___x_46_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__2, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__2_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__2);
v___x_47_ = lean_alloc_ctor(3, 3, 0);
lean_ctor_set(v___x_47_, 0, v___x_46_);
lean_ctor_set(v___x_47_, 1, v___x_45_);
lean_ctor_set(v___x_47_, 2, v___x_44_);
return v___x_47_;
}
}
static lean_object* _init_l_Lean_termMacro_x2etrace_x5b___x5d__(void){
_start:
{
lean_object* v___x_48_; 
v___x_48_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__21, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__21_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__21);
return v___x_48_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0(void){
_start:
{
lean_object* v___x_49_; 
v___x_49_ = lean_mk_string_unchecked("Parser", 6, 6);
return v___x_49_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1(void){
_start:
{
lean_object* v___x_50_; 
v___x_50_ = lean_mk_string_unchecked("Term", 4, 4);
return v___x_50_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__2(void){
_start:
{
lean_object* v___x_51_; 
v___x_51_ = lean_mk_string_unchecked("app", 3, 3);
return v___x_51_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__3(void){
_start:
{
lean_object* v___x_52_; lean_object* v___x_53_; lean_object* v___x_54_; lean_object* v___x_55_; lean_object* v___x_56_; 
v___x_52_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__2, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__2_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__2);
v___x_53_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1);
v___x_54_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0);
v___x_55_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0);
v___x_56_ = l_Lean_Name_mkStr4(v___x_55_, v___x_54_, v___x_53_, v___x_52_);
return v___x_56_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__4(void){
_start:
{
lean_object* v___x_57_; 
v___x_57_ = lean_mk_string_unchecked("Macro.trace", 11, 11);
return v___x_57_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__5(void){
_start:
{
lean_object* v___x_58_; lean_object* v___x_59_; 
v___x_58_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__4, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__4_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__4);
v___x_59_ = l_String_toRawSubstring_x27(v___x_58_);
return v___x_59_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__6(void){
_start:
{
lean_object* v___x_60_; 
v___x_60_ = lean_mk_string_unchecked("Macro", 5, 5);
return v___x_60_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__7(void){
_start:
{
lean_object* v___x_61_; 
v___x_61_ = lean_mk_string_unchecked("trace", 5, 5);
return v___x_61_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__8(void){
_start:
{
lean_object* v___x_62_; lean_object* v___x_63_; lean_object* v___x_64_; 
v___x_62_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__7, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__7_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__7);
v___x_63_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__6, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__6_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__6);
v___x_64_ = l_Lean_Name_mkStr2(v___x_63_, v___x_62_);
return v___x_64_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__9(void){
_start:
{
lean_object* v___x_65_; lean_object* v___x_66_; lean_object* v___x_67_; lean_object* v___x_68_; 
v___x_65_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__7, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__7_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__7);
v___x_66_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__6, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__6_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__6);
v___x_67_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0);
v___x_68_ = l_Lean_Name_mkStr3(v___x_67_, v___x_66_, v___x_65_);
return v___x_68_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__10(void){
_start:
{
lean_object* v___x_69_; lean_object* v___x_70_; lean_object* v___x_71_; 
v___x_69_ = lean_box(0);
v___x_70_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__9, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__9_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__9);
v___x_71_ = lean_alloc_ctor(1, 2, 0);
lean_ctor_set(v___x_71_, 0, v___x_70_);
lean_ctor_set(v___x_71_, 1, v___x_69_);
return v___x_71_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__11(void){
_start:
{
lean_object* v___x_72_; lean_object* v___x_73_; lean_object* v___x_74_; 
v___x_72_ = lean_box(0);
v___x_73_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__10, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__10_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__10);
v___x_74_ = lean_alloc_ctor(1, 2, 0);
lean_ctor_set(v___x_74_, 0, v___x_73_);
lean_ctor_set(v___x_74_, 1, v___x_72_);
return v___x_74_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__12(void){
_start:
{
lean_object* v___x_75_; 
v___x_75_ = lean_mk_string_unchecked("null", 4, 4);
return v___x_75_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__13(void){
_start:
{
lean_object* v___x_76_; lean_object* v___x_77_; 
v___x_76_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__12, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__12_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__12);
v___x_77_ = l_Lean_Name_mkStr1(v___x_76_);
return v___x_77_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__14(void){
_start:
{
lean_object* v___x_78_; 
v___x_78_ = lean_mk_string_unchecked("paren", 5, 5);
return v___x_78_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__15(void){
_start:
{
lean_object* v___x_79_; lean_object* v___x_80_; lean_object* v___x_81_; lean_object* v___x_82_; lean_object* v___x_83_; 
v___x_79_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__14, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__14_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__14);
v___x_80_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1);
v___x_81_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0);
v___x_82_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0);
v___x_83_ = l_Lean_Name_mkStr4(v___x_82_, v___x_81_, v___x_80_, v___x_79_);
return v___x_83_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__16(void){
_start:
{
lean_object* v___x_84_; 
v___x_84_ = lean_mk_string_unchecked("hygienicLParen", 14, 14);
return v___x_84_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__17(void){
_start:
{
lean_object* v___x_85_; lean_object* v___x_86_; lean_object* v___x_87_; lean_object* v___x_88_; lean_object* v___x_89_; 
v___x_85_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__16, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__16_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__16);
v___x_86_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1);
v___x_87_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0);
v___x_88_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0);
v___x_89_ = l_Lean_Name_mkStr4(v___x_88_, v___x_87_, v___x_86_, v___x_85_);
return v___x_89_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__18(void){
_start:
{
lean_object* v___x_90_; 
v___x_90_ = lean_mk_string_unchecked("(", 1, 1);
return v___x_90_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__19(void){
_start:
{
lean_object* v___x_91_; 
v___x_91_ = lean_mk_string_unchecked("hygieneInfo", 11, 11);
return v___x_91_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__20(void){
_start:
{
lean_object* v___x_92_; lean_object* v___x_93_; 
v___x_92_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__19, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__19_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__19);
v___x_93_ = l_Lean_Name_mkStr1(v___x_92_);
return v___x_93_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__21(void){
_start:
{
lean_object* v___x_94_; 
v___x_94_ = lean_mk_string_unchecked("", 0, 0);
return v___x_94_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__22(void){
_start:
{
lean_object* v___x_95_; lean_object* v___x_96_; 
v___x_95_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__21, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__21_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__21);
v___x_96_ = l_String_toRawSubstring_x27(v___x_95_);
return v___x_96_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__23(void){
_start:
{
lean_object* v___x_97_; lean_object* v___x_98_; 
v___x_97_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0);
v___x_98_ = l_Lean_Name_mkStr1(v___x_97_);
return v___x_98_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__24(void){
_start:
{
lean_object* v___x_99_; lean_object* v___x_100_; 
v___x_99_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__23, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__23_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__23);
v___x_100_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v___x_100_, 0, v___x_99_);
return v___x_100_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__25(void){
_start:
{
lean_object* v___x_101_; lean_object* v___x_102_; lean_object* v___x_103_; 
v___x_101_ = lean_box(0);
v___x_102_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__24, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__24_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__24);
v___x_103_ = lean_alloc_ctor(1, 2, 0);
lean_ctor_set(v___x_103_, 0, v___x_102_);
lean_ctor_set(v___x_103_, 1, v___x_101_);
return v___x_103_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__26(void){
_start:
{
lean_object* v___x_104_; 
v___x_104_ = lean_mk_string_unchecked("termS!_", 7, 7);
return v___x_104_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__27(void){
_start:
{
lean_object* v___x_105_; lean_object* v___x_106_; 
v___x_105_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__26, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__26_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__26);
v___x_106_ = l_Lean_Name_mkStr1(v___x_105_);
return v___x_106_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__28(void){
_start:
{
lean_object* v___x_107_; 
v___x_107_ = lean_mk_string_unchecked("s!", 2, 2);
return v___x_107_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__29(void){
_start:
{
lean_object* v___x_108_; 
v___x_108_ = lean_mk_string_unchecked(")", 1, 1);
return v___x_108_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__30(void){
_start:
{
lean_object* v___x_109_; 
v___x_109_ = lean_mk_string_unchecked("quotedName", 10, 10);
return v___x_109_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__31(void){
_start:
{
lean_object* v___x_110_; lean_object* v___x_111_; lean_object* v___x_112_; lean_object* v___x_113_; lean_object* v___x_114_; 
v___x_110_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__30, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__30_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__30);
v___x_111_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__1);
v___x_112_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__0);
v___x_113_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__0);
v___x_114_ = l_Lean_Name_mkStr4(v___x_113_, v___x_112_, v___x_111_, v___x_110_);
return v___x_114_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__32(void){
_start:
{
lean_object* v___x_115_; 
v___x_115_ = lean_mk_string_unchecked("`", 1, 1);
return v___x_115_;
}
}
static lean_object* _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__33(void){
_start:
{
lean_object* v___x_116_; 
v___x_116_ = lean_mk_string_unchecked(".", 1, 1);
return v___x_116_;
}
}
LEAN_EXPORT lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1(lean_object* v_x_117_, lean_object* v_a_118_, lean_object* v_a_119_){
_start:
{
lean_object* v___x_120_; uint8_t v___x_121_; 
v___x_120_ = lean_obj_once(&l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__2, &l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__2_once, _init_l_Lean_termMacro_x2etrace_x5b___x5d___00__closed__2);
lean_inc(v_x_117_);
v___x_121_ = l_Lean_Syntax_isOfKind(v_x_117_, v___x_120_);
if (v___x_121_ == 0)
{
lean_object* v___x_122_; lean_object* v___x_123_; 
lean_dec(v_x_117_);
v___x_122_ = lean_box(1);
v___x_123_ = lean_alloc_ctor(1, 2, 0);
lean_ctor_set(v___x_123_, 0, v___x_122_);
lean_ctor_set(v___x_123_, 1, v_a_119_);
return v___x_123_;
}
else
{
lean_object* v_quotContext_124_; lean_object* v_currMacroScope_125_; lean_object* v_ref_126_; lean_object* v___x_127_; lean_object* v_id_128_; lean_object* v___x_129_; lean_object* v___x_130_; uint8_t v___x_131_; lean_object* v___x_132_; lean_object* v___x_133_; lean_object* v___x_134_; lean_object* v___x_135_; lean_object* v___x_136_; lean_object* v___x_137_; lean_object* v___x_138_; lean_object* v___x_139_; lean_object* v___x_140_; lean_object* v___y_142_; lean_object* v___x_165_; lean_object* v___x_166_; lean_object* v___x_167_; 
v_quotContext_124_ = lean_ctor_get(v_a_118_, 1);
v_currMacroScope_125_ = lean_ctor_get(v_a_118_, 2);
v_ref_126_ = lean_ctor_get(v_a_118_, 5);
v___x_127_ = lean_unsigned_to_nat(1u);
v_id_128_ = l_Lean_Syntax_getArg(v_x_117_, v___x_127_);
v___x_129_ = lean_unsigned_to_nat(3u);
v___x_130_ = l_Lean_Syntax_getArg(v_x_117_, v___x_129_);
lean_dec(v_x_117_);
v___x_131_ = 0;
v___x_132_ = l_Lean_SourceInfo_fromRef(v_ref_126_, v___x_131_);
v___x_133_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__3, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__3_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__3);
v___x_134_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__5, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__5_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__5);
v___x_135_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__8, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__8_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__8);
lean_inc(v_currMacroScope_125_);
lean_inc(v_quotContext_124_);
v___x_136_ = l_Lean_addMacroScope(v_quotContext_124_, v___x_135_, v_currMacroScope_125_);
v___x_137_ = lean_box(0);
v___x_138_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__11, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__11_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__11);
lean_inc(v___x_132_);
v___x_139_ = lean_alloc_ctor(3, 4, 0);
lean_ctor_set(v___x_139_, 0, v___x_132_);
lean_ctor_set(v___x_139_, 1, v___x_134_);
lean_ctor_set(v___x_139_, 2, v___x_136_);
lean_ctor_set(v___x_139_, 3, v___x_138_);
v___x_140_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__13, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__13_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__13);
v___x_165_ = l_Lean_TSyntax_getId(v_id_128_);
lean_dec(v_id_128_);
v___x_166_ = lean_erase_macro_scopes(v___x_165_);
lean_inc(v___x_166_);
v___x_167_ = l___private_Init_Meta_Defs_0__Lean_getEscapedNameParts_x3f(v___x_137_, v___x_166_);
if (lean_obj_tag(v___x_167_) == 0)
{
lean_object* v___x_168_; 
v___x_168_ = l_Lean_quoteNameMk(v___x_166_);
v___y_142_ = v___x_168_;
goto v___jp_141_;
}
else
{
lean_object* v_val_169_; lean_object* v___x_170_; lean_object* v___x_171_; lean_object* v___x_172_; lean_object* v___x_173_; lean_object* v___x_174_; lean_object* v___x_175_; lean_object* v___x_176_; lean_object* v___x_177_; lean_object* v___x_178_; lean_object* v___x_179_; 
lean_dec(v___x_166_);
v_val_169_ = lean_ctor_get(v___x_167_, 0);
lean_inc(v_val_169_);
lean_dec_ref(v___x_167_);
v___x_170_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__31, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__31_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__31);
v___x_171_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__32, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__32_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__32);
v___x_172_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__33, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__33_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__33);
v___x_173_ = lean_string_intercalate(v___x_172_, v_val_169_);
v___x_174_ = lean_string_append(v___x_171_, v___x_173_);
lean_dec_ref(v___x_173_);
v___x_175_ = lean_box(2);
v___x_176_ = l_Lean_Syntax_mkNameLit(v___x_174_, v___x_175_);
v___x_177_ = lean_mk_empty_array_with_capacity(v___x_127_);
v___x_178_ = lean_array_push(v___x_177_, v___x_176_);
v___x_179_ = lean_alloc_ctor(1, 3, 0);
lean_ctor_set(v___x_179_, 0, v___x_175_);
lean_ctor_set(v___x_179_, 1, v___x_170_);
lean_ctor_set(v___x_179_, 2, v___x_178_);
v___y_142_ = v___x_179_;
goto v___jp_141_;
}
v___jp_141_:
{
lean_object* v___x_143_; lean_object* v___x_144_; lean_object* v___x_145_; lean_object* v___x_146_; lean_object* v___x_147_; lean_object* v___x_148_; lean_object* v___x_149_; lean_object* v___x_150_; lean_object* v___x_151_; lean_object* v___x_152_; lean_object* v___x_153_; lean_object* v___x_154_; lean_object* v___x_155_; lean_object* v___x_156_; lean_object* v___x_157_; lean_object* v___x_158_; lean_object* v___x_159_; lean_object* v___x_160_; lean_object* v___x_161_; lean_object* v___x_162_; lean_object* v___x_163_; lean_object* v___x_164_; 
v___x_143_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__15, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__15_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__15);
v___x_144_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__17, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__17_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__17);
v___x_145_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__18, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__18_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__18);
lean_inc_n(v___x_132_, 9);
v___x_146_ = lean_alloc_ctor(2, 2, 0);
lean_ctor_set(v___x_146_, 0, v___x_132_);
lean_ctor_set(v___x_146_, 1, v___x_145_);
v___x_147_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__20, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__20_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__20);
v___x_148_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__22, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__22_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__22);
v___x_149_ = lean_box(0);
lean_inc(v_currMacroScope_125_);
lean_inc(v_quotContext_124_);
v___x_150_ = l_Lean_addMacroScope(v_quotContext_124_, v___x_149_, v_currMacroScope_125_);
v___x_151_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__25, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__25_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__25);
v___x_152_ = lean_alloc_ctor(3, 4, 0);
lean_ctor_set(v___x_152_, 0, v___x_132_);
lean_ctor_set(v___x_152_, 1, v___x_148_);
lean_ctor_set(v___x_152_, 2, v___x_150_);
lean_ctor_set(v___x_152_, 3, v___x_151_);
v___x_153_ = l_Lean_Syntax_node1(v___x_132_, v___x_147_, v___x_152_);
v___x_154_ = l_Lean_Syntax_node2(v___x_132_, v___x_144_, v___x_146_, v___x_153_);
v___x_155_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__27, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__27_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__27);
v___x_156_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__28, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__28_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__28);
v___x_157_ = lean_alloc_ctor(2, 2, 0);
lean_ctor_set(v___x_157_, 0, v___x_132_);
lean_ctor_set(v___x_157_, 1, v___x_156_);
v___x_158_ = l_Lean_Syntax_node2(v___x_132_, v___x_155_, v___x_157_, v___x_130_);
v___x_159_ = lean_obj_once(&l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__29, &l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__29_once, _init_l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___closed__29);
v___x_160_ = lean_alloc_ctor(2, 2, 0);
lean_ctor_set(v___x_160_, 0, v___x_132_);
lean_ctor_set(v___x_160_, 1, v___x_159_);
v___x_161_ = l_Lean_Syntax_node3(v___x_132_, v___x_143_, v___x_154_, v___x_158_, v___x_160_);
v___x_162_ = l_Lean_Syntax_node2(v___x_132_, v___x_140_, v___y_142_, v___x_161_);
v___x_163_ = l_Lean_Syntax_node2(v___x_132_, v___x_133_, v___x_139_, v___x_162_);
v___x_164_ = lean_alloc_ctor(0, 2, 0);
lean_ctor_set(v___x_164_, 0, v___x_163_);
lean_ctor_set(v___x_164_, 1, v_a_119_);
return v___x_164_;
}
}
}
}
LEAN_EXPORT lean_object* l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1___boxed(lean_object* v_x_180_, lean_object* v_a_181_, lean_object* v_a_182_){
_start:
{
lean_object* v_res_183_; 
v_res_183_ = l_Lean___aux__Init__MacroTrace______macroRules__Lean__termMacro_x2etrace_x5b___x5d____1(v_x_180_, v_a_181_, v_a_182_);
lean_dec_ref(v_a_181_);
return v_res_183_;
}
}
lean_object* runtime_initialize_Init_Notation(uint8_t builtin);
lean_object* runtime_initialize_Init_Data_ToString_Macro(uint8_t builtin);
static bool _G_runtime_initialized = false;
LEAN_EXPORT lean_object* runtime_initialize_Init_MacroTrace(uint8_t builtin) {
lean_object * res;
if (_G_runtime_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_runtime_initialized = true;
res = runtime_initialize_Init_Notation(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_Init_Data_ToString_Macro(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
return lean_io_result_mk_ok(lean_box(0));
}
lean_object* runtime_initialize_Init_Meta(uint8_t builtin);
static bool _G_meta_initialized = false;
LEAN_EXPORT lean_object* meta_initialize_Init_MacroTrace(uint8_t builtin) {
lean_object * res;
if (_G_meta_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_meta_initialized = true;
res = runtime_initialize_Init_Meta(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
l_Lean_termMacro_x2etrace_x5b___x5d__ = _init_l_Lean_termMacro_x2etrace_x5b___x5d__();
lean_mark_persistent(l_Lean_termMacro_x2etrace_x5b___x5d__);
return lean_io_result_mk_ok(lean_box(0));
}
lean_object* initialize_Init_Meta(uint8_t builtin);
lean_object* initialize_Init_Notation(uint8_t builtin);
lean_object* initialize_Init_Data_ToString_Macro(uint8_t builtin);
static bool _G_initialized = false;
LEAN_EXPORT lean_object* initialize_Init_MacroTrace(uint8_t builtin) {
lean_object * res;
if (_G_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_initialized = true;
res = initialize_Init_Meta(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Init_Notation(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Init_Data_ToString_Macro(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_Init_MacroTrace(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = meta_initialize_Init_MacroTrace(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
return initialize_Init_MacroTrace(builtin);
}
#ifdef __cplusplus
}
#endif
