// Lean compiler output
// Module: Lean.Elab.Tactic.TreeTacAttr
// Imports: public import Lean.Meta.Tactic.Simp
#include <lean/lean.h>
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wunused-label"
#elif defined(__GNUC__) && !defined(__CLANG__)
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#endif
#ifdef __cplusplus
extern "C" {
#endif
lean_object* l_Lean_Name_mkStr3(lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Name_mkStr1(lean_object*);
lean_object* l_Lean_Meta_registerSimpAttr(lean_object*, lean_object*, lean_object*);
static lean_once_cell_t l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__0_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__0_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_;
static lean_once_cell_t l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__1_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__1_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_;
static lean_once_cell_t l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__2_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__2_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_;
static lean_once_cell_t l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__3_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__3_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_;
static lean_once_cell_t l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__4_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__4_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_;
static lean_once_cell_t l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__5_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__5_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_;
static lean_once_cell_t l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__6_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__6_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_;
LEAN_EXPORT lean_object* l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_();
LEAN_EXPORT lean_object* l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2____boxed(lean_object*);
LEAN_EXPORT lean_object* l_treeTacExt;
static lean_object* _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__0_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_(void){
_start:
{
lean_object* v___x_1_; 
v___x_1_ = lean_mk_string_unchecked("Std", 3, 3);
return v___x_1_;
}
}
static lean_object* _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__1_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_(void){
_start:
{
lean_object* v___x_2_; 
v___x_2_ = lean_mk_string_unchecked("Internal", 8, 8);
return v___x_2_;
}
}
static lean_object* _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__2_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_(void){
_start:
{
lean_object* v___x_3_; 
v___x_3_ = lean_mk_string_unchecked("tree_tac", 8, 8);
return v___x_3_;
}
}
static lean_object* _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__3_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_(void){
_start:
{
lean_object* v___x_4_; lean_object* v___x_5_; lean_object* v___x_6_; lean_object* v___x_7_; 
v___x_4_ = lean_obj_once(&l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__2_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_, &l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__2_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once, _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__2_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_);
v___x_5_ = lean_obj_once(&l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__1_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_, &l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__1_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once, _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__1_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_);
v___x_6_ = lean_obj_once(&l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__0_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_, &l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__0_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once, _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__0_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_);
v___x_7_ = l_Lean_Name_mkStr3(v___x_6_, v___x_5_, v___x_4_);
return v___x_7_;
}
}
static lean_object* _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__4_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_(void){
_start:
{
lean_object* v___x_8_; 
v___x_8_ = lean_mk_string_unchecked("simp theorems used by internal DTreeMap lemmas", 46, 46);
return v___x_8_;
}
}
static lean_object* _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__5_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_(void){
_start:
{
lean_object* v___x_9_; 
v___x_9_ = lean_mk_string_unchecked("treeTacExt", 10, 10);
return v___x_9_;
}
}
static lean_object* _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__6_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_(void){
_start:
{
lean_object* v___x_10_; lean_object* v___x_11_; 
v___x_10_ = lean_obj_once(&l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__5_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_, &l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__5_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once, _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__5_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_);
v___x_11_ = l_Lean_Name_mkStr1(v___x_10_);
return v___x_11_;
}
}
LEAN_EXPORT lean_object* l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_(){
_start:
{
lean_object* v___x_13_; lean_object* v___x_14_; lean_object* v___x_15_; lean_object* v___x_16_; 
v___x_13_ = lean_obj_once(&l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__3_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_, &l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__3_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once, _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__3_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_);
v___x_14_ = lean_obj_once(&l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__4_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_, &l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__4_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once, _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__4_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_);
v___x_15_ = lean_obj_once(&l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__6_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_, &l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__6_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2__once, _init_l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn___closed__6_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_);
v___x_16_ = l_Lean_Meta_registerSimpAttr(v___x_13_, v___x_14_, v___x_15_);
return v___x_16_;
}
}
LEAN_EXPORT lean_object* l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2____boxed(lean_object* v_a_17_){
_start:
{
lean_object* v_res_18_; 
v_res_18_ = l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_();
return v_res_18_;
}
}
lean_object* runtime_initialize_Lean_Meta_Tactic_Simp(uint8_t builtin);
static bool _G_runtime_initialized = false;
LEAN_EXPORT lean_object* runtime_initialize_Lean_Elab_Tactic_TreeTacAttr(uint8_t builtin) {
lean_object * res;
if (_G_runtime_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_runtime_initialized = true;
res = runtime_initialize_Lean_Meta_Tactic_Simp(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = l___private_Lean_Elab_Tactic_TreeTacAttr_0__initFn_00___x40_Lean_Elab_Tactic_TreeTacAttr_1062317674____hygCtx___hyg_2_();
if (lean_io_result_is_error(res)) return res;
l_treeTacExt = lean_io_result_get_value(res);
lean_mark_persistent(l_treeTacExt);
lean_dec_ref(res);
return lean_io_result_mk_ok(lean_box(0));
}
static bool _G_meta_initialized = false;
LEAN_EXPORT lean_object* meta_initialize_Lean_Elab_Tactic_TreeTacAttr(uint8_t builtin) {
lean_object * res;
if (_G_meta_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_meta_initialized = true;
return lean_io_result_mk_ok(lean_box(0));
}
lean_object* initialize_Lean_Meta_Tactic_Simp(uint8_t builtin);
static bool _G_initialized = false;
LEAN_EXPORT lean_object* initialize_Lean_Elab_Tactic_TreeTacAttr(uint8_t builtin) {
lean_object * res;
if (_G_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_initialized = true;
res = initialize_Lean_Meta_Tactic_Simp(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_Lean_Elab_Tactic_TreeTacAttr(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = meta_initialize_Lean_Elab_Tactic_TreeTacAttr(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
return initialize_Lean_Elab_Tactic_TreeTacAttr(builtin);
}
#ifdef __cplusplus
}
#endif
